### ISSUE TITLE
CORS Issue in Google Chrome

### ISSUE THREAD

**Issue by tspoor** [Chordian/deepsid#15]
Access to XMLHttpRequest at 'http://ftp.acc.umu.se/mirror/media/Oakvalley//soasc/hvsc/052/FLAC/MUSICIANS/A/A-Man/Smoove_Groove_T001.sid_CSG8580R5.flac' from origin 'http://deepsid.chordian.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Chordian** [comment]
Issue closed since SOASC is no longer supported by DeepSID.
