### ISSUE TITLE
Feature Request: Fix to rating to a small hinderence when rating tunes.

### ISSUE THREAD

**Issue by Jacko-UK** [Chordian/deepsid#30]
Firstly, thank you, a great Web App, I have been a regular user for a while now and a SID fan (and of your tunes) since my C128 in '87  and then on the Amiga PlaySID and later the DOS SIDPlayer.👍🙂👌

Little things I have found over the last four-plus years would be great.

1. **Ability to change the * rating from within the main player panel** (as I find the highlighted tune always scrolls down out of view when playing through most tune lists - I tend to go through authors and rate every track in turn, but that's just me).

2. **Ability to auto-center the current highlighted tune in the list** so it is always visible.

I hope these suggestions might be of some use to other users.  Please take this as positive feedback on a great app.

On behalf of all the regular users out there, a well done and thanks for all your years of effort, it is greatly appreciated. 👍
-Stephen.

**Comment by Chordian** [comment]
And thanks to you for finding my web site useful. 😊

1. I'm not sure what you mean by player panel, do you mean in the control/info boxes above the browse area?

2. There's a switch in the settings, "Auto-progress should select and center the next song as it proceeds to it", but now that I test it again it does seem to have issues. I'll note down to check up on it.

**Comment by Jacko-UK** [comment]
Thanks for getting to me, I was thinking something like this...

![image](https://github.com/user-attachments/assets/e47abe30-e1ad-42ff-8788-f3686e32a77b)

Also (which could be a **new 'ECO' feature** 🍃), I find whilst the page is hidden (e.g. minimised or the tab is not visible) the CPU usage is 5x less and the GPU usage drops to 0; this is the same when in minimal 'P key' mode.  So, I have got into the habit of deliberately hiding the page when playing when using less powerful laptops or tablets (especially when running on battery).  I'm presuming there is timed event refresh for the GUI, I don't suppose the timer refresh period/rate can made tweakable (say in settings) so it could be reduced down so that it is more 'eco' with a reduced CPU footprint?  Obviously the downside would be that GUI responsiveness would be vastly reduced, but if takes a sec or so to control (play/skip etc.) the track then, me personally, I would be happy with that.

Whilst visible:

![image](https://github.com/user-attachments/assets/7beddcda-9056-4ac7-a6fb-b89cbead9179)

Whilst hidden: (note: there is no loss of sound quality)

![image](https://github.com/user-attachments/assets/1cf28a45-67aa-48e0-851e-813a62fbda35)

Thanks again for your efforts. 👍🙂

**Comment by Chordian** [comment]
Having stars for the song in the info area in top is a good idea, I'll note it down in my ToDo.

**Comment by Chordian** [comment]
You can now rate songs in the info box as suggested.

**Comment by Jacko-UK** [comment]
Cheers!  It works perfectly. 👌

I have mitigated the CPU load by changing the player option to Lemon's MP3 Files, which drops the workload, and has the bonus of a rewind.

Great work, very happy, thanks.  😁👍
